[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
the_good_place = "6WQ3EeKJnFj2TbCQPu563WVKhrN5od3VhUZfv66PHiTP"

[registry]
# url = "https://api.testnet.sonic.game"
url = "Localnet"

[provider]
# cluster = "https://api.testnet.sonic.game"
cluster = "Localnet"
wallet = "~/metaloot-keypair.json"

[test]
upgradeable = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
